/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/swarm` | `/swarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wealth` | `/wealth`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/swarm` | `/swarm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wealth` | `/wealth`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/security${`?${string}` | `#${string}` | ''}` | `/security${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/swarm${`?${string}` | `#${string}` | ''}` | `/swarm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wealth${`?${string}` | `#${string}` | ''}` | `/wealth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/swarm` | `/swarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wealth` | `/wealth`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
